version: 2

jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck

    steps:
      - checkout

      - run:
          name: Run Shellcheck
          command: shellcheck -s bash docs/*.sh prepare-vms/azure/*.sh prepare-vms/azure/packer/*.sh

  psscriptanalyzer:
    docker:
      - image: microsoft/powershell
    
    steps:
      - checkout
      
      - run:
          name: Run PSScriptAnalyzer
          command: |
            pwsh -c 'Install-Module PSScriptAnalyzer -Force;
              $Results = Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning;
              $Results
              if ($Results) {
                Throw "Test failed. PSScriptAnalyzer found issues."
              }
            '

  packer-validate:
    docker:
      - image: hashicorp/packer:1.2.4

    steps:
      - checkout

      - run:
          name: Run Packer validate
          command: |
            cd prepare-vms/azure/packer
            for filename in *.json; do
              packer validate $filename
            done

  packer: &packer
    docker:
      - image: hashicorp/packer:1.2.4

    steps:
      - checkout

      - run:
          name: Run Packer build on Azure
          command: ./prepare-vms/azure/packer/circle-build.sh
          no_output_timeout: 1800

  terraform-validate:
    docker:
      - image: hashicorp/terraform:0.11.7

    steps:
      - checkout

      - run:
          name: Run Terraform validate
          command: |
            cd prepare-vms/azure/terraform
            apk add pwgen
            ./create-passwords.sh
            terraform init
            terraform validate

  terraform: &terraform
    docker:
      - image: hashicorp/terraform:0.11.7

    steps:
      - checkout

      - run:
          name: Build infrastructure
          command: ./prepare-vms/azure/terraform/circle-build.sh

  build-windows-2016:
    <<: *packer
    environment:
      - PACKER_TEMPLATE: "windows_2016"

  build-windows-2019:
    <<: *packer
    environment:
      - PACKER_TEMPLATE: "windows_2019"

workflows:
  version: 2

  test-and-build:
    jobs:
      - shellcheck
      - psscriptanalyzer
      - packer-validate
      - terraform-validate
      - build-windows-2016:
          requires:
            - shellcheck
            - psscriptanalyzer
            - packer-validate
            - terraform-validate
          filters:
            tags:
              ignore: /.*/
            branches:
              only:
                - master
      - terraform:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*-.*/
